### ISSUE TITLE
Has this been tested on Windows?

### ISSUE THREAD

**Issue by dkeller93** [InsightSoftwareConsortium/ITKDevelopmentEnvironment#1]
Hello, I'm trying to get an ITK development environment setup on my windows machine. I tried the vagrant setup, but vagrant up hangs at `Calling state.highstate... (this may take a while)`. I let it run for almost a day and it hangs. Are there prebuilt ITKDevelopmentEnvironment's for VirtualBox? Thanks.

**Comment by thewtex** [comment]
@dkeller93 The vagrant scripts have not been tested in quite some time. The VirtualBox VM's they created are archived here:

  http://midas3.kitware.com/midas/folder/9388

However, a more recent version of ITK is recommended.  If you are using Windows, then build from source as recommended in the ITK Software Guide.  If you want to use Linux in a VirtualBox VM, then most distributions come with ITK packages (search for `insighttoolkit`) or it can be built from source there, too.

**Comment by dkeller93** [comment]
Trying to build on Windows has been a nightmare. The InsightSoftwareGuide said that it only works with VS 8 9 and 10. I can't get my windows environment to cooperate with the VS compilers (registry hell?). Another reason why I've been seeking out VMs is that I'm working in a group and wish to maintain a uniform development environment.

Our main goal is to use the DeformableModelSimplexMesh InsightApplication. While researching my problem, I came across this VM http://midas.kitware.com/item/view/450 which after git cloning the ITKApps from source `ccmake ~/ITKApps/SuperBuild`, complained about subversion not being installed. So I ran `sudo apt-get install subversion -y`, but I got a bunch of 404's and got a similar result with `sudo apt-get update`. So I concluded that VM is too old.

I'll look through those VMs you showed me to discover if those allow me to build the InsightApplications (or preferably already have them built). Our team has been trying to build InsightApplications for a while and find the problem very frustrating. Thanks for your help!

**Comment by thewtex** [comment]
Are you looking at an old version of ITK? ITK now works with all recent versions of Visual Studio.  The Git version of ITK, and soon the most recent release, will add support for Visual Studio 14.

Yes, that VM is likely too old, and the repositories may no longer be available.

You will likely want to use a recent Linux distribution with the most recent version of ITKApps. Try using Docker with the `debian` image.

**Comment by dkeller93** [comment]
That's strange. The software guide says the most up to date version it will support is 10. Where is the document that describes the new VS compatibility? As for the versions of ITK (besides using the prebuild VMs) we've been cloning from the most recent source: http://itk.org/ITK(Apps).git.

One other issue is that when I `ccmake ~/ITKApps/Superbuild` and then `make`, git clone requests are made with the `git://` protocol which is unfortunately blocked on my university network. Would it be wrong to change those urls to `http://`?

**Comment by thewtex** [comment]
Where do you see the Visual Studio supported version in The Software Guide?


Compiler support is shown on the Nightly Dashboard:

  https://open.cdash.org/index.php?project=Insight#


To use the `http://` protocol instead of the `git://` protocol, set
`USE_GIT_PROTOCOL` to `OFF` in your ITKApps Superbuild CMake configuration.

**Comment by dkeller93** [comment]
Thanks for catching my rookie mistake on the cmake config. I'm now getting an error (after `ccmake ~/ITKApps/Superbuild` and `make`):`undefined reference to glXGetProcAddress`. Are there windows executables for the InsightApplications?

**Comment by thewtex** [comment]
If your app requires VTK / graphics, it will require extra configuration with Docker.

Windows executables for InsightApplications should be built from source.

**Comment by dkeller93** [comment]
I got the superbuild to run without errors on one of the sample VMs, however we can't find the deformablemodelsimplexmesh executable. The app does require VTK / graphics.

**Comment by thewtex** [comment]
I'll see if I can add VTK render support to a Docker image.

**Comment by dkeller93** [comment]
Are there virtual machines with the ITKApps superbuild already built?

**Comment by thewtex** [comment]
One of the previous workshop builds may have them.

**Comment by jhlegarreta** [comment]
@thewtex This thread has quite some time. May be outdated/be closed?

**Comment by thewtex** [comment]
Good idea, @jhlegarreta 

Closing because I do not have time to follow up with this.

If someone is interested in taking it up, the infrastructure to support generation of graphical apps in Docker is at

  https://github.com/thewtex/docker-opengl
